<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.5.2 setup script
 * Date: Tue, 17 Jan 2017 01:44:00 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'vulpix';
$cfg['Servers'][$i]['password'] = 'vulpix';

/* End of servers configuration */

$cfg['blowfish_secret'] = ';5n1|%C\'"aqDLZpeY+cFhq$nk)={)D[J';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>